### PR TITLE
Local testing instructions

### PR DESCRIPTION
**Pull request by dLobatog**
Signed-off-by: Daniel Lobato Garcia <me@daniellobato.me>

### CODE REVIEW

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by esakaiev** [comment]
test this please

**Comment by gravitypriest** [comment]
I recently copied the dev instructions from the mojo doc to the readme. Please reopen with just the Makefile changes.

**Pull request closed without merging**
