### PR TITLE
test: Add integration tests for the Ansible playbook verifier

### PR DESCRIPTION
**Pull request by m-horky**
* Card ID: CCT-546

### CODE REVIEW

**Review by ptoscano — COMMENTED** [review]
The new test generally looks OK; that said, IMHO it seems it can be simplified a bit, removing extra "wrapping" and bits:
- the helper `verify_playbook()` seems only a mere wrapping around `subprocess.run()`; I'd simply fold it in `test_official_playbook()`, in case there is nothing more that needs to use that helper
- in `verify_playbook()`: some arguments are passed directly to `subprocess.run()` and some others are in a `extra_args` list; I'd fold `extra_args` directly in `subprocess.run()`
- in `verify_playbook()`: passing `check=True` to `subprocess.run()` avoids the need to `assert result.returncode == 0`, as a failing execution will raise CalledProcessError whose content can be inspected/logged
- in `verify_playbook()`: you don't need to use `shutil.which()`, `subprocess.run()` (or whatever it uses internally) will do that automatically; it will not make any difference anyway, since both ways (`subprocess.run()` and `shutil.which()`) use `$PATH` to locale the executable

**Comment by m-horky** [comment]
> the helper `verify_playbook()` seems only a mere wrapping around `subprocess.run()`; I'd simply fold it in `test_official_playbook()`, in case there is nothing more that needs to use that helper

I had plans to add additional test(s) that would run it with non-Red Hat GPG key, but I had to reprioritize. Even if, don't you think this better separates test setup from the actual call? I can merge them if not.

> in `verify_playbook()`: some arguments are passed directly to `subprocess.run()` and some others are in a `extra_args` list; I'd fold `extra_args` directly in `subprocess.run()`

This was also to make it cleaner -- the extra arguments are not required for the functionality, they are just a result of how limited the CLI API is. Again, if it doesn't make sense, I can rewrite it.

> in `verify_playbook()`: passing `check=True` to `subprocess.run()` avoids the need to `assert result.returncode == 0`, as a failing execution will raise CalledProcessError whose content can be inspected/logged

That way you don't get to see the stderr of the command, pytest only reports that the subcommand exited with non-zero status. This makes it much easier to debug.

> in `verify_playbook()`: you don't need to use `shutil.which()`, `subprocess.run()` (or whatever it uses internally) will do that automatically; it will not make any difference anyway, since both ways (`subprocess.run()` and `shutil.which()`) use `$PATH` to locale the executable

Fair point. Will address this once we agreed on what to do with the rest of your notes.

**Comment by ptoscano** [comment]
> Even if, don't you think this better separates test setup from the actual call?

If there is anything more planned, maybe; since so far the test needed seems "run the validation and check it works", I'd keep things simple for now. Refactoring is easy, in case there is a need later on.

> This was also to make it cleaner -- the extra arguments are not required for the functionality, they are just a result of how limited the CLI API is. Again, if it doesn't make sense, I can rewrite it.

More than "doesn't make sense", what I looked at is how this is used in other workers (so far only rhc-worker-playbook and rhc-worker-script), and they both call `insights-client` with the same set of parameters (the ones in the test). Hence, for me the verification call is made by all the parameters at the same time, with no separation in two "types".

> That way you don't get to see the stderr of the command, pytest only reports that the subcommand exited with non-zero status.

If stderr is collected, then the raisen CalledProcessError has stderr too, which will be printed when the exception is stringified.

**Comment by m-horky** [comment]
> I'd keep things simple for now.
> the verification call is made by all the parameters at the same time

Ack.

> If stderr is collected, then the raisen CalledProcessError has stderr too, which will be printed when the exception is stringified.

That's not what I'm seeing. The returned `CalledProcessError` only displays the arguments and status.

**Comment by ptoscano** [comment]
IMHO the newly added test generally work fine. I think the commit message and/or the test  would deserve a bit more verbosity on what's being added (and why), however it is not a hard stop from me.

On OSes with Python 3.12 the stderr is filled with warnings for code that is in insights-core:
```
/etc/insights-client/rpm.egg/insights/parsers/__init__.py:160: SyntaxWarning: invalid escape sequence '\ '
```
The new test explicitly requires that stderr is empty, which thus causes the failure. Is this (stderr as empty) a hard requirement for considering the playbook verifier working/successful?
Also, looking at the current two users of the verifier (rhc-worker-playbook and rhc-worker-script):
- none of them actually checks for stderr when the validation succeeds
- both of them seem to print stderr on failure

so maybe we can ignore stderr on success?

**Comment by ptoscano** [comment]
Hmm there used to be
```python
@pytest.mark.xfail(
    condition=sys.version_info >= (3, 12),
    reason="Verification is known to be broken on Python 3.12+",
)
```
in previous versions of this PR, and indeed the new `test_official_playbook` test fails on OSes with Python >= 3.12 (so Fedora >= 39); should that mark be added back, until the verifier is fixed?

**Comment by m-horky** [comment]
Good call, I was testing it with locally patched egg, I forgot to put it back.

**Review by ptoscano — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
