### PR TITLE
Load proxy settings from RHSM conf

### PR DESCRIPTION
**Pull request by Glutexo**
If _auto_config_ is enabled, use RHSM proxy configuration if set. Otherwise, let Requests use the environment configuration as it used to do. This is a rather naïve subset of the Core proxy configuration to fix it for a specific environment reported as [RHCLOUD-11760](https://issues.redhat.com/browse/RHCLOUD-11760).

~~Draft, because there are no tests yet.~~

### CODE REVIEW

**Review by subpop — APPROVED** [review]
Looks good to me.

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
I added a some more unit and integration tests. Also added _PYTHONPATH_ to _pytest.sh_, so it can import _insights_client_. May I ask for a fresh review, @subpop, @gravitypriest?

**Comment by Glutexo** [comment]
Oh. My tests failed under Python 2.7. I kind of expected that. Unfortunately `make check` is not verbose and there is no clue what happened. I am afraid mock is not available in there, but I need to try to reproduce.

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Review by subpop — APPROVED** [review]
Tests! Looks great. Good on ya, mate!

**Comment by Glutexo** [comment]
QE confirmed this works.

**Pull request merged**
