### PR TITLE
Add checkin option to documentation 📝

### PR DESCRIPTION
**Pull request by Glutexo**
Added _--checkin_ documentation to the manual page.

https://issues.redhat.com/browse/RHCLOUD-11884

### CODE REVIEW

**Comment by Glutexo** [comment]
The pipeline failed at `python get-pip.py`. Not related to this pull request.

**Comment by Glutexo** [comment]
test this please

**Review by gravitypriest — APPROVED** [review]

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by Glutexo** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by patchkez** [comment]
test this please

**Comment by Glutexo** [comment]
Hmm. For this to be release, an egg version containing the check-in feature needs to be bundled.

**Pull request merged**
